language: rust
sudo: false

matrix:
  include:
    - rust: 1.15.0
    - rust: 1.31.0
    - rust: stable
    - rust: beta
    - rust: nightly
      script:
        - cargo test
        - cargo test --no-default-features
        - cargo test --features span-locations
        - RUSTFLAGS='--cfg procmacro2_semver_exempt' cargo test
        - RUSTFLAGS='--cfg procmacro2_semver_exempt' cargo test --no-default-features
        - RUSTFLAGS='-Z allow-features=' cargo test
        - cargo update -Z minimal-versions && cargo build
    - rust: nightly
      name: WebAssembly
      install: rustup target add wasm32-unknown-unknown
      script: cargo test --target wasm32-unknown-unknown --no-run

before_script:
  - set -o errexit

script:
  - cargo test
  - cargo test --no-default-features
  - cargo test --features span-locations
  - RUSTFLAGS='--cfg procmacro2_semver_exempt' cargo test
  - RUSTFLAGS='--cfg procmacro2_semver_exempt' cargo test --no-default-features

notifications:
  email:
    on_success: never
